# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeamProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TeamProject
	pod 'Starscream', '~> 3.0.2'
	pod 'SwiftyJSON', '~> 4.0'
end
